export const MOCK_RECIPES = [
  {
    idMeal: "52772",
    strMeal: "Teriyaki Chicken Casserole",
    strCategory: "Chicken",
    strArea: "Japanese",
    strInstructions: "Preheat oven to 350 degrees F (175 degrees C).\r\nCombine rice, chicken, broccoli, and mixed vegetables in a 9x13 inch baking dish.\r\nIn a small bowl, whisk together soy sauce, brown sugar, ginger, garlic powder, and honey. Pour over the casserole.\r\nBake in the preheated oven for 30 minutes, or until bubbling. Serve warm.",
    strMealThumb: "https://www.themealdb.com/images/media/meals/wvpsxx1468256210.jpg",
    strYoutube: "https://www.youtube.com/watch?v=4aZr5hZXP_s",
    strIngredient1: "Chicken Breast",
    strIngredient2: "Broccoli",
    strIngredient3: "Soy Sauce",
    strIngredient4: "Brown Sugar",
    strIngredient5: "Garlic Powder",
    strIngredient6: "Ginger",
    strIngredient7: "Honey",
    strIngredient8: "Rice",
    strMeasure1: "500g",
    strMeasure2: "1 head",
    strMeasure3: "1/2 cup",
    strMeasure4: "2 tbsp",
    strMeasure5: "1 tsp",
    strMeasure6: "1/2 tsp",
    strMeasure7: "1 tbsp",
    strMeasure8: "1 cup",
  },
  {
    idMeal: "52855",
    strMeal: "Banana Pancakes",
    strCategory: "Dessert",
    strArea: "American",
    strInstructions: "In a bowl, mash the bananas with a fork until smooth.\r\nWhisk in the eggs, milk, and melted butter.\r\nIn another bowl, mix flour, sugar, baking powder, and a pinch of salt.\r\nCombine wet and dry ingredients. Stir gently.\r\nHeat a non-stick pan over medium heat. Pour batter and cook until bubbles form. Flip and cook until golden brown.",
    strMealThumb: "https://unsplash.com/photos/brown-bread-with-blue-berries-on-top-I-X7DAAcZns",
    strYoutube: "https://www.youtube.com/watch?v=kSKtb2Pv-_U",
    strIngredient1: "Bananas",
    strIngredient2: "Eggs",
    strIngredient3: "Milk",
    strIngredient4: "Flour",
    strIngredient5: "Baking Powder",
    strIngredient6: "Butter",
    strIngredient7: "Sugar",
    strMeasure1: "2 medium",
    strMeasure2: "2",
    strMeasure3: "1/2 cup",
    strMeasure4: "1 cup",
    strMeasure5: "1 tsp",
    strMeasure6: "1 tbsp",
    strMeasure7: "1 tbsp",
  },
  {
    idMeal: "52818",
    strMeal: "Chicken Tikka Masala",
    strCategory: "Chicken",
    strArea: "Indian",
    strInstructions: "Marinate chicken in yogurt and spices for 1 hour. Grill or bake chicken until browned.\r\nFor the sauce: sauté onions, garlic, and ginger in butter. Add cumin, garam masala, and turmeric.\r\nAdd canned tomatoes and simmer for 15 minutes. Stir in heavy cream.\r\nAdd the grilled chicken to the sauce and simmer for another 10 minutes. Garnish with cilantro.",
    strMealThumb: "https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg",
    strYoutube: "https://www.youtube.com/watch?v=1F9XNstc2Q0",
    strIngredient1: "Chicken Breast",
    strIngredient2: "Yogurt",
    strIngredient3: "Garlic",
    strIngredient4: "Ginger",
    strIngredient5: "Garam Masala",
    strIngredient6: "Canned Tomatoes",
    strIngredient7: "Heavy Cream",
    strIngredient8: "Cilantro",
    strMeasure1: "800g",
    strMeasure2: "1 cup",
    strMeasure3: "4 cloves",
    strMeasure4: "1 tbsp",
    strMeasure5: "2 tsp",
    strMeasure6: "400g",
    strMeasure7: "1/2 cup",
    strMeasure8: "Garnish",
  },
  {
    idMeal: "52906",
    strMeal: "Flamiche",
    strCategory: "Vegetarian",
    strArea: "French",
    strInstructions: "Roll out the pastry dough and fit it into a tart tin.\r\nSauté the leeks in butter until soft but not browned, then let cool.\r\nWhisk eggs, crème fraîche, and nutmeg together. Season with salt and pepper.\r\nStir leeks into the egg mix and pour into pastry case.\r\nBake for 35 minutes at 400°F (200°C) until golden and set.",
    strMealThumb: "https://1.bp.blogspot.com/-sAYZgTrNJTw/WsyTaiXfyBI/AAAAAAAApnE/MRITNks9WEQLrdDnM_ySReIDcyPSrHigQCLcBGAs/s1600/bacon-leek-flamiche-edit-3413.jpg",
    strYoutube: "https://www.youtube.com/watch?v=Kz48B-V_f00",
    strIngredient1: "Puff Pastry",
    strIngredient2: "Leeks",
    strIngredient3: "Butter",
    strIngredient4: "Eggs",
    strIngredient5: "Crème Fraîche",
    strIngredient6: "Nutmeg",
    strMeasure1: "1 sheet",
    strMeasure2: "3 large",
    strMeasure3: "2 tbsp",
    strMeasure4: "3",
    strMeasure5: "1/2 cup",
    strMeasure6: "Pinch",
  },
  {
    idMeal: "53013",
    strMeal: "Big Mac",
    strCategory: "Beef",
    strArea: "American",
    strInstructions: "For the sauce: mix mayonnaise, sweet relish, mustard, white wine vinegar, garlic powder, onion powder, and paprika.\r\nForm ground beef into thin patties. Season with salt and grill until cooked through.\r\nToast burger buns. Assemble burger: bottom bun, sauce, onions, lettuce, cheese, patty, middle bun, sauce, onions, lettuce, pickles, patty, top bun.",
    strMealThumb: "https://www.pexels.com/photo/big-delicious-hamburger-on-board-15476375/",
    strYoutube: "https://www.youtube.com/watch?v=d_K22dSt8qA",
    strIngredient1: "Minced Beef",
    strIngredient2: "Burger Buns",
    strIngredient3: "Mayonnaise",
    strIngredient4: "Sweet Relish",
    strIngredient5: "Yellow Mustard",
    strIngredient6: "Cheddar Cheese",
    strIngredient7: "Lettuce",
    strMeasure1: "400g",
    strMeasure2: "2 double-deck",
    strMeasure3: "1/2 cup",
    strMeasure4: "2 tbsp",
    strMeasure5: "1 tbsp",
    strMeasure6: "2 slices",
    strMeasure7: "1/2 cup shredded",
  },
  {
    idMeal: "99001",
    strMeal: "Classic Masala Dosa",
    strCategory: "Vegetarian",
    strArea: "Indian",
    strInstructions: "Wash and soak rice and urad dal with fenugreek seeds in water for 6 hours.\r\nGrind them separately to a smooth batter. Mix them together, add salt, and ferment overnight.\r\nFor the potato filling: Boil and mash potatoes. Sauté mustard seeds, curry leaves, ginger, onions, and green chillies in oil. Add turmeric, salt, and the potatoes. Mix well.\r\nHeat a non-stick flat griddle (tawa). Spread a ladle of batter thinly in a circular motion.\r\nDrizzle ghee around the edges. Cook until crispy and golden. Place the potato filling in the center, fold, and serve hot with coconut chutney.",
    strMealThumb: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=600&auto=format&fit=crop&q=60",
    strYoutube: "https://youtu.be/IDNtiYTd7_M?si=DuGLODwZVjzWHoUP",
    strIngredient1: "Idli Rice",
    strIngredient2: "Urad Dal",
    strIngredient3: "Fenugreek Seeds",
    strIngredient4: "Potatoes",
    strIngredient5: "Onions",
    strIngredient6: "Mustard Seeds",
    strIngredient7: "Curry Leaves",
    strIngredient8: "Turmeric Powder",
    strIngredient9: "Green Chillies",
    strIngredient10: "Ghee",
    strMeasure1: "2 cups",
    strMeasure2: "1/2 cup",
    strMeasure3: "1 tsp",
    strMeasure4: "4 medium",
    strMeasure5: "1 large",
    strMeasure6: "1 tsp",
    strMeasure7: "10 leaves",
    strMeasure8: "1/2 tsp",
    strMeasure9: "2 chopped",
    strMeasure10: "3 tbsp",
  },
  {
    idMeal: "99002",
    strMeal: "Steamed Idli with Sambar",
    strCategory: "Vegetarian",
    strArea: "Indian",
    strInstructions: "Soak idli rice and urad dal separately for 5 hours. Grind dal to a fluffy batter, and rice to a slightly coarse batter. Combine, add salt, and ferment for 8-12 hours.\r\nPour the batter into greased idli molds and steam for 10-12 minutes until toothpick inserted comes out clean.\r\nFor Sambar: Boil toor dal with turmeric. Boil mixed vegetables (carrots, drumsticks, pumpkin) in tamarind water with sambar powder.\r\nAdd the mashed dal to the vegetable pot and simmer. Temper with mustard seeds, curry leaves, and dry red chillies in oil. Serve hot idlis dipped in sambar.",
    strMealThumb: "https://bluenilekitchen.com/wp-content/uploads/2024/06/IdliSambarWebsite.jpg",
    strYoutube: "https://youtu.be/uCCmi8j_6_E?si=qSPQqu1RZg-fXjZW",
    strIngredient1: "Idli Rice",
    strIngredient2: "Urad Dal",
    strIngredient3: "Toor Dal",
    strIngredient4: "Tamarind Paste",
    strIngredient5: "Sambar Powder",
    strIngredient6: "Mustard Seeds",
    strIngredient7: "Curry Leaves",
    strIngredient8: "Carrots",
    strIngredient9: "Drumsticks",
    strIngredient10: "Oil",
    strMeasure1: "3 cups",
    strMeasure2: "1 cup",
    strMeasure3: "1/2 cup",
    strMeasure4: "1 tbsp",
    strMeasure5: "2 tbsp",
    strMeasure6: "1 tsp",
    strMeasure7: "8 leaves",
    strMeasure8: "1 sliced",
    strMeasure9: "1 cut pieces",
    strMeasure10: "1 tbsp",
  },
  {
    idMeal: "99003",
    strMeal: "Chicken Chettinad",
    strCategory: "Chicken",
    strArea: "Indian",
    strInstructions: "Roast whole spices: coriander seeds, cumin seeds, fennel seeds, black peppercorns, dry red chillies, cinnamon, and cloves until aromatic. Grind to a fine paste with fresh grated coconut and a little water.\r\nHeat oil in a pan, sauté fennel seeds, curry leaves, and onions until golden brown.\r\nAdd ginger-garlic paste and tomatoes, and cook until mushy.\r\nAdd chicken pieces, turmeric powder, and salt. Stir well.\r\nPour in the ground Chettinad spice paste and 1 cup of water. Cover and simmer for 25 minutes until chicken is tender and gravy is thick. Garnish with fresh coriander.",
    strMealThumb: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop&q=60",
    strYoutube: "https://youtu.be/RGN5kdNqzGc?si=zMKKi2h52Z9saB8G",
    strIngredient1: "Chicken",
    strIngredient2: "Coriander Seeds",
    strIngredient3: "Fennel Seeds",
    strIngredient4: "Black Peppercorns",
    strIngredient5: "Dry Red Chillies",
    strIngredient6: "Grated Coconut",
    strIngredient7: "Curry Leaves",
    strIngredient8: "Onions",
    strIngredient9: "Tomatoes",
    strIngredient10: "Ginger-Garlic Paste",
    strMeasure1: "800g",
    strMeasure2: "2 tbsp",
    strMeasure3: "1 tsp",
    strMeasure4: "1 tsp",
    strMeasure5: "4",
    strMeasure6: "1/2 cup",
    strMeasure7: "12 leaves",
    strMeasure8: "2 chopped",
    strMeasure9: "2 pureed",
    strMeasure10: "1 tbsp",
  },
  {
    idMeal: "99004",
    strMeal: "Kerala Coconut Fish Curry",
    strCategory: "Seafood",
    strArea: "Indian",
    strInstructions: "Clean and cut the fish into medium pieces.\r\nSoak dry tamarind (Kudampuli) in 1/2 cup warm water.\r\nIn a blender, grind grated coconut, small shallots, chili powder, coriander powder, and turmeric powder with a little water to make a smooth paste.\r\nIn an earthen clay pot, add the coconut paste, tamarind water, sliced ginger, slit green chillies, curry leaves, and another cup of water. Bring to a simmer.\r\nAdd the fish pieces and salt. Cover and cook on medium-low heat for 12-15 minutes until the fish is tender.\r\nIn a small pan, heat coconut oil, crackle mustard seeds, fenugreek seeds, and curry leaves. Pour this tempering over the fish curry, let it sit covered for 10 minutes, and serve with steamed rice.",
    strMealThumb: "https://seafood-portal.com/thumb/768/kerala-fish-curry-a-creamy-coconut-dream.webp",
    strYoutube: "https://youtu.be/aROKVWwp43U?si=D4eNnnOt75J0T-iS",
    strIngredient1: "Fish Fillet",
    strIngredient2: "Grated Coconut",
    strIngredient3: "Tamarind",
    strIngredient4: "Shallots",
    strIngredient5: "Ginger",
    strIngredient6: "Green Chillies",
    strIngredient7: "Mustard Seeds",
    strIngredient8: "Curry Leaves",
    strIngredient9: "Coconut Oil",
    strIngredient10: "Chili Powder",
    strMeasure1: "500g",
    strMeasure2: "1 cup",
    strMeasure3: "2 pieces",
    strMeasure4: "6 sliced",
    strMeasure5: "1 inch shredded",
    strMeasure6: "2 slit",
    strMeasure7: "1/2 tsp",
    strMeasure8: "10 leaves",
    strMeasure9: "2 tbsp",
    strMeasure10: "1 tbsp",
  },
  {
    idMeal: "99005",
    strMeal: "Medu Vada",
    strCategory: "Starter",
    strArea: "Indian",
    strInstructions: "Soak urad dal in water for 3 hours. Drain completely.\r\nGrind the dal adding very little ice-cold water, a tablespoon at a time, to get a thick, fluffy batter.\r\nAerate the batter by whipping it with your hands for 5 minutes until it floats in water.\r\nStir in chopped green chillies, ginger, curry leaves, black peppercorns, onions, coriander leaves, and salt.\r\nWet your palms. Take a small ball of batter, flatten it slightly, and make a hole in the center with your thumb.\r\nSlide it gently into hot oil. Deep fry on medium heat until golden brown and crispy on both sides. Serve hot with coconut chutney.",
    strMealThumb: "https://img.magnific.com/free-photo/south-indian-vada-medu-vada-dal-vadai-plate-bowl-isolated-plain_466689-1580.jpg?size=626&ext=jpg",
    strYoutube: "https://youtu.be/qgYTSsxe7W4?si=qvNkY9QvGBZQcmZb",
    strIngredient1: "Urad Dal",
    strIngredient2: "Green Chillies",
    strIngredient3: "Ginger",
    strIngredient4: "Curry Leaves",
    strIngredient5: "Black Peppercorns",
    strIngredient6: "Onions",
    strIngredient7: "Coriander Leaves",
    strIngredient8: "Salt",
    strIngredient9: "Oil for Frying",
    strMeasure1: "1 cup",
    strMeasure2: "2 chopped",
    strMeasure3: "1 tsp minced",
    strMeasure4: "8 leaves",
    strMeasure5: "1/2 tsp",
    strMeasure6: "1/4 cup chopped",
    strMeasure7: "2 tbsp",
    strMeasure8: "1 tsp",
    strMeasure9: "As needed",
  },
  {
    idMeal: "99006",
    strMeal: "Boeuf Bourguignon",
    strCategory: "Beef",
    strArea: "French",
    strInstructions: "Heat olive oil in a Dutch oven and sauté bacon lardons until golden brown. Remove and set aside.\r\nPat beef chuck dry with paper towels, season with salt and pepper, and sear in the bacon fat until brown on all sides. Remove beef.\r\nSauté sliced carrots and onion in the same pot. Add minced garlic and cook for 1 minute.\r\nReturn beef and bacon to the pot, sprinkle with flour, and toss to coat. Cook for 2 minutes.\r\nPour in red wine (Pinot Noir) and beef stock. Stir in tomato paste, thyme, and bay leaf. Bring to a simmer, cover, and bake in a preheated oven at 325°F (160°C) for 2 to 3 hours.\r\nIn the last 30 minutes, sauté mushrooms and pearl onions in butter. Stir them into the beef stew. Simmer for 15 minutes before serving with mashed potatoes or crusty bread.",
    strMealThumb: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=600&auto=format&fit=crop&q=60",
    strYoutube: "https://youtu.be/_Bx9P32tdaM?si=7XYCqeemLNx6skoL",
    strIngredient1: "Beef Chuck",
    strIngredient2: "Bacon",
    strIngredient3: "Red Wine",
    strIngredient4: "Beef Broth",
    strIngredient5: "Tomato Paste",
    strIngredient6: "Flour",
    strIngredient7: "Carrots",
    strIngredient8: "Onion",
    strIngredient9: "Garlic",
    strIngredient10: "Mushrooms",
    strMeasure1: "1kg",
    strMeasure2: "150g lardons",
    strMeasure3: "2 cups",
    strMeasure4: "2 cups",
    strMeasure5: "1 tbsp",
    strMeasure6: "2 tbsp",
    strMeasure7: "2 sliced",
    strMeasure8: "1 chopped",
    strMeasure9: "3 cloves",
    strMeasure10: "200g sliced",
  },
  {
    idMeal: "99007",
    strMeal: "French Onion Soup",
    strCategory: "Starter",
    strArea: "French",
    strInstructions: "Melt butter in a large deep pot over medium heat. Add thinly sliced onions and thyme.\r\nCook slowly, stirring occasionally, for 45-50 minutes until onions are completely soft, deep golden brown, and caramelized.\r\nAdd minced garlic and cook for 2 minutes. Pour in dry white wine to deglaze the pan, scraping up all browned bits.\r\nAdd beef broth, bay leaf, and Worcestershire sauce. Bring to a boil, then reduce heat and simmer for 25 minutes.\r\nTo serve: ladle hot soup into oven-safe bowls. Place a slice of toasted French baguette on top of each bowl. Cover generously with grated Gruyere cheese.\r\nPlace under a broiler for 3-4 minutes until cheese is melted, bubbling, and golden brown.",
    strMealThumb: "https://images.unsplash.com/photo-1583577547338-048731776a3e?w=600&auto=format&fit=crop&q=60",
    strYoutube: "https://youtu.be/1qRir364aNk?si=J9TQY39dr8AePXB0",
    strIngredient1: "Yellow Onions",
    strIngredient2: "Butter",
    strIngredient3: "White Wine",
    strIngredient4: "Beef Broth",
    strIngredient5: "Garlic",
    strIngredient6: "Baguette",
    strIngredient7: "Gruyere Cheese",
    strIngredient8: "Thyme",
    strIngredient9: "Worcestershire",
    strMeasure1: "5 large",
    strMeasure2: "3 tbsp",
    strMeasure3: "1/2 cup",
    strMeasure4: "6 cups",
    strMeasure5: "3 cloves",
    strMeasure6: "6 slices",
    strMeasure7: "1.5 cups grated",
    strMeasure8: "2 sprigs",
    strMeasure9: "1 tsp",
  },
  {
    idMeal: "99008",
    strMeal: "Coq au Vin",
    strCategory: "Chicken",
    strArea: "French",
    strInstructions: "Season chicken thighs with salt and pepper. Fry bacon in a large casserole dish until crispy. Remove bacon.\r\nSear chicken thighs in the bacon fat until golden brown on both sides. Remove chicken.\r\nSauté sliced onions, carrots, and garlic in the pot. Return chicken and bacon to the casserole.\r\nPour in red Burgundy wine and chicken stock. Add tomato paste, thyme, and bay leaf. Bring to a simmer, cover, and cook on low heat for 40 minutes.\r\nIn a separate pan, sauté pearl onions and mushrooms in butter. Add to the chicken casserole and simmer for another 10 minutes.\r\nBlend butter and flour (beurre manié) and stir into the bubbling sauce to thicken slightly. Garnish with parsley and serve.",
    strMealThumb: "https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=600&auto=format&fit=crop&q=60",
    strYoutube: "https://youtu.be/hJswLfXL_GA?si=gEVS3zDfjVbuVEFJ",
    strIngredient1: "Chicken Thighs",
    strIngredient2: "Bacon",
    strIngredient3: "Red Wine",
    strIngredient4: "Chicken Stock",
    strIngredient5: "Mushrooms",
    strIngredient6: "Pearl Onions",
    strIngredient7: "Butter",
    strIngredient8: "Flour",
    strIngredient9: "Carrots",
    strIngredient10: "Thyme",
    strMeasure1: "6 pieces",
    strMeasure2: "100g",
    strMeasure3: "2 cups",
    strMeasure4: "1 cup",
    strMeasure5: "150g",
    strMeasure6: "10 small",
    strMeasure7: "2 tbsp",
    strMeasure8: "2 tbsp",
    strMeasure9: "1 sliced",
    strMeasure10: "3 sprigs",
  },
  {
    idMeal: "99009",
    strMeal: "Classic Apple Pie",
    strCategory: "Dessert",
    strArea: "American",
    strInstructions: "In a large bowl, mix thinly sliced peeled apples, lemon juice, white sugar, brown sugar, flour, cinnamon, nutmeg, and ginger. Let sit for 20 minutes.\r\nRoll out one disk of pie pastry and place it into a 9-inch pie dish.\r\nFill the crust with the apple mixture, piling them slightly high in the center. Dot the top with small pieces of butter.\r\nRoll out the second disk of pastry and place it over the apples. Cut vents in the top crust or create a lattice pattern.\r\nTrim and crimp the edges to seal. Brush the top with beaten egg wash and sprinkle with sugar.\r\nBake at 425°F (220°C) for 15 minutes, then reduce temperature to 375°F (190°C) and bake for another 40-45 minutes until the crust is golden and the filling is bubbling. Cool before serving.",
    strMealThumb: "https://images.unsplash.com/photo-1519869325930-281384150729?w=600&auto=format&fit=crop&q=60",
    strYoutube: "https://youtu.be/eazZvfyhYK0?si=CMkjTKhuAimbmC6a",
    strIngredient1: "Apples (Granny Smith)",
    strIngredient2: "Pie Crusts",
    strIngredient3: "Sugar",
    strIngredient4: "Brown Sugar",
    strIngredient5: "Flour",
    strIngredient6: "Cinnamon",
    strIngredient7: "Nutmeg",
    strIngredient8: "Butter",
    strIngredient9: "Lemon Juice",
    strIngredient10: "Egg Wash",
    strMeasure1: "6 medium",
    strMeasure2: "2 pre-rolled",
    strMeasure3: "1/2 cup",
    strMeasure4: "1/2 cup",
    strMeasure5: "2 tbsp",
    strMeasure6: "1 tsp",
    strMeasure7: "1/4 tsp",
    strMeasure8: "2 tbsp",
    strMeasure9: "1 tbsp",
    strMeasure10: "1 egg beaten",
  },
  {
    idMeal: "99010",
    strMeal: "Southern Fried Chicken",
    strCategory: "Chicken",
    strArea: "American",
    strInstructions: "In a large bowl, whisk together buttermilk, hot sauce, salt, black pepper, and garlic powder.\r\nAdd chicken drumsticks, cover, and refrigerate to marinate for at least 4 hours (or overnight).\r\nIn a large zip-top bag or shallow dish, mix flour, cornstarch, paprika, garlic powder, onion powder, cayenne pepper, salt, and pepper.\r\nRemove chicken from buttermilk, letting excess drip off, and dredge thoroughly in the seasoned flour mixture. Press to adhere.\r\nHeat vegetable oil in a deep heavy skillet or Dutch oven to 350°F (175°C).\r\nFry chicken in batches for 12-15 minutes, turning occasionally, until the crust is crispy and golden brown, and the internal temperature reaches 165°F (74°C). Drain on a wire rack and serve warm.",
    strMealThumb: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=60",
    strYoutube: "https://youtu.be/bFQi-BN9xvc?si=zoH-SJnCguIfLh6R",
    strIngredient1: "Chicken Drumsticks",
    strIngredient2: "Buttermilk",
    strIngredient3: "Flour",
    strIngredient4: "Cornstarch",
    strIngredient5: "Paprika",
    strIngredient6: "Garlic Powder",
    strIngredient7: "Onion Powder",
    strIngredient8: "Cayenne Pepper",
    strIngredient9: "Vegetable Oil",
    strIngredient10: "Hot Sauce",
    strMeasure1: "8 pieces",
    strMeasure2: "2 cups",
    strMeasure3: "2 cups",
    strMeasure4: "1/4 cup",
    strMeasure5: "2 tsp",
    strMeasure6: "2 tsp",
    strMeasure7: "1 tsp",
    strMeasure8: "1/2 tsp",
    strMeasure9: "For deep frying",
    strMeasure10: "1 tbsp",
  },
];